In [137]:
import re
import numpy as np
import pandas as pd

In [ ]:
# robots = """p=0,4 v=3,-3
# p=6,3 v=-1,-3
# p=10,3 v=-1,2
# p=2,0 v=2,-1
# p=0,0 v=1,3
# p=3,0 v=-2,-2
# p=7,6 v=-1,-3
# p=3,0 v=-1,-2
# p=9,3 v=2,3
# p=7,3 v=-1,2
# p=2,4 v=2,-3
# p=9,5 v=-3,-3"""

# rows = 7  # max y
# cols = 11  # max x

# # robots = """p=2,4 v=2,-3"""

In [196]:
with open("input.txt") as f:
    robots = f.read().strip()

robots = robots.split("\n")
robots = [
    [list(map(int, re.findall(r"-?\d{1,3}", x))) for x in r.split(" ")] for r in robots
]

rows = 103
cols = 101

In [99]:
robots

[[[91, 23], [98, -65]],
 [[100, 68], [-43, 14]],
 [[33, 76], [55, 34]],
 [[83, 21], [14, 67]],
 [[59, 43], [-65, 77]],
 [[2, 89], [-53, 61]],
 [[22, 83], [44, 85]],
 [[54, 82], [13, 72]],
 [[72, 70], [-81, 43]],
 [[9, 89], [42, -76]],
 [[80, 10], [-79, -19]],
 [[65, 86], [-38, -35]],
 [[67, 41], [-87, 72]],
 [[39, 82], [-20, -80]],
 [[76, 20], [-4, 98]],
 [[44, 22], [56, 63]],
 [[91, 13], [-74, 19]],
 [[48, 56], [-15, 69]],
 [[61, 30], [99, 74]],
 [[10, 38], [55, 80]],
 [[24, 61], [59, -72]],
 [[98, 50], [74, 95]],
 [[17, 33], [3, 87]],
 [[91, 70], [17, -7]],
 [[79, 92], [31, -49]],
 [[8, 30], [-73, -95]],
 [[9, 34], [-83, -34]],
 [[62, 17], [21, 29]],
 [[47, 51], [-56, 38]],
 [[57, 64], [86, 96]],
 [[92, 1], [18, 43]],
 [[16, 72], [89, -69]],
 [[85, 96], [-23, -91]],
 [[7, 25], [95, -50]],
 [[95, 71], [30, -47]],
 [[23, 5], [19, -91]],
 [[79, 40], [87, 73]],
 [[12, 84], [63, 6]],
 [[30, 79], [-92, 85]],
 [[64, 36], [91, 70]],
 [[63, 6], [26, 50]],
 [[64, 76], [-41, -80]],
 [[61, 6], [

In [101]:
final_coordinates = []

for r in robots:
    x, y = r[0]
    dx, dy = r[1]
    for _ in range(100):
        x += dx
        if x > cols-1:
            x -= cols
        if x < 0:
            x += cols
        y += dy
        if y > rows-1:
            y -= rows
        if y < 0:
            y += rows
    final_coordinates.append((x, y))


In [102]:
mid_rows = rows // 2
mid_cols = cols // 2

q1, q2, q3, q4 = [list() for _ in range(4)]
for c in final_coordinates:
    x, y = c
    if x > mid_cols and y > mid_rows:
        q1.append(c)
    elif x < mid_cols and y > mid_rows:
        q2.append(c)
    elif x < mid_cols and y < mid_rows:
        q3.append(c)
    elif x > mid_cols and y < mid_rows:
        q4.append(c)

safety_factor = 1
for q in [q1, q2, q3, q4]:
    safety_factor *= len(q)

print(safety_factor)

221655456


In [97]:
final_coordinates

grid = np.zeros((rows, cols), dtype=int)

for c in final_coordinates:
    x, y = c
    grid[y, x] += 1

print(grid)

[[0 0 0 0 0 0 2 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 2 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0]]


In [198]:
with open("input.txt") as f:
    robots = f.read().strip()

robots = robots.split("\n")
robots = [
    [list(map(int, re.findall(r"-?\d{1,3}", x))) for x in r.split(" ")] for r in robots
]

rows = 103
cols = 101

results = []
iterations = cols * rows
district_size = 20

for i in range(iterations):
    for r in robots:
        x, y = r[0]
        dx, dy = r[1]
        x += dx
        if x > cols - 1:
            x -= cols
        if x < 0:
            x += cols
        y += dy
        if y > rows - 1:
            y -= rows
        if y < 0:
            y += rows
        r[0] = [x, y]

    positions = [r[0] for r in robots]

    # break up plot into 20x20 districts
    districts = {}
    for x, y in positions:
        district_x = (x // district_size) * district_size
        district_y = (y // district_size) * district_size
        district_key = (district_x, district_y)
        if district_key not in districts:
            districts[district_key] = 0
        districts[district_key] += 1

    max_district_count = max(districts.values())

    results.append((i, max_district_count, positions))

In [199]:
pd.DataFrame(results).sort_values(1, ascending=False)

0    1                                                  2
7857  7857  169  [[50, 30], [51, 76], [44, 66], [5, 74], [46, 8...
787    787   73  [[50, 97], [51, 79], [44, 88], [5, 81], [46, 5...
6948  6948   73  [[50, 96], [51, 19], [44, 60], [5, 44], [46, 3...
181    181   73  [[50, 38], [51, 41], [44, 84], [5, 61], [46, 4...
9372  9372   72  [[50, 23], [51, 68], [44, 76], [5, 21], [46, 4...
...    ...  ...                                                ...
7622  7622   23  [[48, 61], [56, 82], [47, 7], [48, 88], [70, 1...
7256  7256   23  [[35, 58], [38, 5], [16, 26], [75, 80], [24, 5...
206    206   23  [[76, 61], [87, 82], [5, 7], [52, 88], [37, 17...
2891  2891   22  [[0, 18], [75, 77], [18, 39], [70, 42], [40, 4...
7416  7416   22  [[60, 61], [26, 82], [29, 7], [93, 88], [27, 1...

[10403 rows x 3 columns]

In [202]:
result = results[7857][2]
grid = np.array([
    ["." for _ in range(cols)] for _ in range(rows)
])

for x, y in result:
    grid[y, x] = "X"

print(i)
for r in grid:
    print("".join(map(str, r)))


10402
X........XX..................X.......................................................................
.................................................................................................X...
.............................................X.......................................................
................X................XX..................X....................X..........................
.......X.............................................................................................
........................................................................X............................
.....................................................................................................
.....................................................................................................
.........................................X...........................................................
..............X..............................................X..............